# Generated by Django 4.1.7 on 2023-04-04 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0005_alter_company_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='incon_class',
        ),
    ]
