# Generated by Django 4.1.7 on 2023-04-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0006_remove_sociallink_incon_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
