# Generated by Django 4.1.7 on 2023-04-04 09:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('vitrine', '0007_sociallink_icon_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(max_length=100, verbose_name='adresse'),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(max_length=100, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='adresse email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone1',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='numéro de téléphone incorrect', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='téléphone 1'),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone2',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='numéro de téléphone incorrect', regex='^\\+?[1-9]\\d{1,14}$')], verbose_name='téléphone 2'),
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(max_length=500, verbose_name='corps'),
        ),
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=30, verbose_name='titre'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='content',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='vitrine.content', verbose_name='contenu'),
        ),
        migrations.AlterField(
            model_name='mediacontent',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='section',
            name='description',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=60, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='icon_class',
            field=models.CharField(max_length=30, verbose_name="classe css de l'icon"),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=100, unique=True, verbose_name='lien'),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='nom'),
        ),
    ]
