# Generated by Django 4.1.7 on 2023-04-04 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0011_company_slogan_alter_region_slug_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slogan',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
