# Generated by Django 4.1.7 on 2023-04-04 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0014_remove_contactfornewletter_created_ad_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AddField(
            model_name='region',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrine.content'),
        ),
    ]
