# Generated by Django 4.1.7 on 2023-04-04 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0015_alter_contact_options_region_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='content',
        ),
        migrations.RemoveField(
            model_name='section',
            name='content',
        ),
        migrations.AddField(
            model_name='content',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrine.region'),
        ),
        migrations.AddField(
            model_name='content',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrine.section'),
        ),
    ]
