# Generated by Django 4.1.7 on 2023-04-04 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0017_rename_section_sector_rename_section_content_sector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'contenu statique', 'verbose_name_plural': 'contenus statiques'},
        ),
    ]
