# Generated by Django 4.1.7 on 2023-04-04 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0019_alter_region_options_alter_sector_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sociallink',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='link', to='vitrine.company'),
        ),
    ]
