# Generated by Django 4.1.7 on 2023-04-05 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0021_alter_sociallink_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['pk'], 'verbose_name': 'reseau social', 'verbose_name_plural': 'reseaux sociaux'},
        ),
        migrations.AlterField(
            model_name='content',
            name='body',
            field=models.TextField(verbose_name='corps'),
        ),
    ]
