# Generated by Django 4.1.7 on 2023-04-05 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0022_alter_sociallink_options_alter_content_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='title',
            field=models.CharField(max_length=80, verbose_name='titre'),
        ),
    ]
