# Generated by Django 4.1.7 on 2023-04-07 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0023_alter_content_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
