# Generated by Django 4.1.7 on 2023-04-07 20:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0032_alter_mediacontent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='pattern_content_home_page',
            field=models.ForeignKey(blank=True, help_text="modèle d'affichage du contenu dans la page d'accueil", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_home_page', to='vitrine.patterncontent', verbose_name="modèle d'affichage dans la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='content',
            name='pattern_content_others_pages',
            field=models.ForeignKey(blank=True, help_text="modèle d'affichage du contenu dans des pages autres que la page d'accueil", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_others_pages', to='vitrine.patterncontent', verbose_name="modèle d'affichage dans d'autres pages"),
        ),
        migrations.AlterField(
            model_name='region',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
