# Generated by Django 4.1.7 on 2023-04-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0033_alter_content_pattern_content_home_page_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactfornewletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
