# Generated by Django 4.1.7 on 2023-04-23 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0034_alter_contactfornewletter_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='company',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='company',
            name='slogan_en',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='company',
            name='slogan_fr',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='slogan'),
        ),
        migrations.AddField(
            model_name='content',
            name='body_en',
            field=models.TextField(null=True, verbose_name='corps'),
        ),
        migrations.AddField(
            model_name='content',
            name='body_fr',
            field=models.TextField(null=True, verbose_name='corps'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_en',
            field=models.CharField(max_length=80, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='content',
            name='title_fr',
            field=models.CharField(max_length=80, null=True, verbose_name='titre'),
        ),
        migrations.AddField(
            model_name='region',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='region',
            name='description_fr',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_en',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='region',
            name='name_fr',
            field=models.CharField(max_length=30, null=True, unique=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='sector',
            name='description_en',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sector',
            name='description_fr',
            field=models.TextField(blank=True, max_length=150, null=True, verbose_name='description'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_en',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='nom'),
        ),
        migrations.AddField(
            model_name='sector',
            name='name_fr',
            field=models.CharField(max_length=60, null=True, unique=True, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='company',
            name='slogan',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='slogan'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='description',
            field=models.TextField(max_length=400, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(max_length=80, verbose_name='nom'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=80, verbose_name='sujet'),
        ),
        migrations.AlterField(
            model_name='content',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrine.region', verbose_name='region'),
        ),
        migrations.AlterField(
            model_name='content',
            name='sector',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrine.sector', verbose_name='secteur'),
        ),
    ]
