# Generated by Django 4.1.7 on 2023-04-30 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0035_company_description_en_company_description_fr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sociallink',
            name='icon_class',
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(blank=True, max_length=100, null=True, unique=True, verbose_name='lien'),
        ),
    ]
