# Generated by Django 4.1.7 on 2023-04-03 14:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrine.content'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone1',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message='numéro de téléphone incorrect', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='company',
            name='phone2',
            field=models.CharField(max_length=16, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='numéro de téléphone incorrect', regex='^\\+?[1-9]\\d{1,14}$')]),
        ),
        migrations.AlterField(
            model_name='region',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='link',
            field=models.URLField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='sociallink',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
