# Generated by Django 4.1.7 on 2023-04-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0003_alter_contact_subject_alter_section_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'default_permissions': ['change', 'view'], 'verbose_name': 'companie', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'contact', 'verbose_name_plural': 'contacts'},
        ),
        migrations.AlterModelOptions(
            name='contactfornewletter',
            options={'verbose_name': 'newsletter', 'verbose_name_plural': 'newsletters'},
        ),
        migrations.AlterModelOptions(
            name='content',
            options={'verbose_name': 'contenu', 'verbose_name_plural': 'contenus'},
        ),
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'verbose_name': 'media du contenu', 'verbose_name_plural': 'medias du contenu'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'région', 'verbose_name_plural': 'régions'},
        ),
        migrations.AlterModelOptions(
            name='section',
            options={'verbose_name': 'secteur', 'verbose_name_plural': 'secteurs'},
        ),
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'reseau social', 'verbose_name_plural': 'reseaux sociaux'},
        ),
    ]
