# Generated by Django 4.1.7 on 2023-04-04 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0008_alter_company_address_alter_company_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(editable=False, max_length=6),
        ),
    ]
