# Generated by Django 4.1.7 on 2023-04-04 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0009_alter_section_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='section',
            name='slug',
            field=models.SlugField(max_length=60),
        ),
    ]
