# Generated by Django 4.1.7 on 2023-04-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_rename_section_article_sector'),
        ('vitrine', '0016_remove_region_content_remove_section_content_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Section',
            new_name='Sector',
        ),
        migrations.RenameField(
            model_name='content',
            old_name='section',
            new_name='sector',
        ),
    ]
