# Generated by Django 4.1.7 on 2023-04-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0018_alter_content_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='region',
            options={'ordering': ['name'], 'verbose_name': 'région', 'verbose_name_plural': 'régions'},
        ),
        migrations.AlterModelOptions(
            name='sector',
            options={'ordering': ['name'], 'verbose_name': 'secteur', 'verbose_name_plural': 'secteurs'},
        ),
        migrations.AlterField(
            model_name='region',
            name='slug',
            field=models.SlugField(editable=False, max_length=30),
        ),
        migrations.AlterField(
            model_name='sector',
            name='slug',
            field=models.SlugField(editable=False, max_length=60),
        ),
    ]
