# Generated by Django 4.1.7 on 2023-04-07 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0024_alter_company_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatternContent',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=80, verbose_name='nom')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
            ],
            options={
                'verbose_name': "modele d'affichage des contenus statiques",
                'verbose_name_plural': "modeles d'affichage des contenus statiques",
            },
        ),
        migrations.AddField(
            model_name='content',
            name='in_home_page',
            field=models.BooleanField(default=False),
        ),
    ]
