# Generated by Django 4.1.7 on 2023-04-07 14:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0025_patterncontent_content_in_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='pattern_content',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrine.patterncontent', verbose_name="modèle d'affichage du contenu"),
        ),
    ]
