# Generated by Django 4.1.7 on 2023-04-07 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0026_content_pattern_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='in_home_page',
            new_name='is_in_home_page',
        ),
    ]
