# Generated by Django 4.1.7 on 2023-04-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0027_rename_in_home_page_content_is_in_home_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, help_text="Plus ce nombre est petit plus le contenu s'affichera en haut avant les autres", null=True, verbose_name="position d'affichage dans le site"),
        ),
        migrations.AlterField(
            model_name='content',
            name='is_in_home_page',
            field=models.BooleanField(default=False, verbose_name="Affiché à la page d'accueil"),
        ),
    ]
