# Generated by Django 4.1.7 on 2023-04-07 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0031_alter_mediacontent_content_alter_mediacontent_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediacontent',
            options={'ordering': ['pk'], 'verbose_name': 'media du contenu', 'verbose_name_plural': 'medias du contenu'},
        ),
        migrations.RemoveField(
            model_name='content',
            name='pattern_content',
        ),
        migrations.AddField(
            model_name='content',
            name='pattern_content_home_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_home_page', to='vitrine.patterncontent', verbose_name="modèle d'affichage du contenu dans la page d'accueil"),
        ),
        migrations.AddField(
            model_name='content',
            name='pattern_content_others_pages',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='content_others_pages', to='vitrine.patterncontent', verbose_name="modèle d'affichage du contenu dans des pages autres que la page d'accueil"),
        ),
        migrations.AlterField(
            model_name='content',
            name='position',
            field=models.PositiveSmallIntegerField(blank=True, default=100, help_text="Plus ce nombre est petit plus le contenu s'affichera en haut avant les autres", verbose_name="position d'affichage dans le site"),
        ),
    ]
