# Generated by Django 4.1.7 on 2023-04-03 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vitrine', '0001_initial'),
        ('blog', '0002_article_banner_alter_comment_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vitrine.section'),
        ),
    ]
