# Generated by Django 4.1.7 on 2023-04-10 04:13

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('blog', '0010_alter_article_published_alter_article_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image de présentation'),
        ),
        migrations.AlterField(
            model_name='article',
            name='banner',
            field=filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_banner', to=settings.FILER_IMAGE_MODEL, verbose_name='image bannière'),
        ),
    ]
