# Generated by Django 4.1.7 on 2023-04-30 12:45

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_article_summary_alter_article_summary_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=django_quill.fields.QuillField(verbose_name="contenu de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_en',
            field=django_quill.fields.QuillField(null=True, verbose_name="contenu de l'article"),
        ),
        migrations.AlterField(
            model_name='article',
            name='content_fr',
            field=django_quill.fields.QuillField(null=True, verbose_name="contenu de l'article"),
        ),
    ]
