# Generated by Django 4.1.7 on 2023-04-04 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_article_slug_alter_tag_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='section',
            new_name='sector',
        ),
    ]
